site_name: opendisk.space
site_url: https://opendisk.space/
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
#    - media: "(prefers-color-scheme)"
#      toggle:
#        icon: material/brightness-auto
#        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  icon:
    logo: fontawesome/regular/floppy-disk
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - content.action.view
plugins:
  - search:
      enabled: true
  - blog:
      blog_dir: .
      authors_profiles: true
      post_url_date_format: yyyy
      archive: false
  - meta

repo_url: https://github.com/Vulp35/opendiskblog
repo_name: Vulp35/opendiskblog
edit_uri: edit/main/docs/
